import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { useTheme } from "@/hooks/useTheme"

const STEPS = [
  {
    number: 1,
    title: "Pick interview type",
    desc: "Choose Technical or HR, add your role and years of experience. PrepZona adapts the difficulty and question style to your profile.",
    detail: "Technical rounds focus on DSA, system design, and domain knowledge. HR rounds cover behavioural, situational, and culture-fit questions.",
  },
  {
    number: 2,
    title: "Mic & camera check",
    desc: "Grant microphone and camera access. See a live preview and run a quick test sentence to confirm speech recognition is working.",
    detail: "We use your browser's built-in speech recognition — no plugins needed. Camera is for self-monitoring only and is never recorded.",
  },
  {
    number: 3,
    title: "Answer 5 questions",
    desc: "Each answer is transcribed in real time, scored by AI, and used to generate the next follow-up question.",
    detail: "You can speak naturally or type. The AI grades on clarity, depth, and relevance — not just keywords. Scores are saved per session.",
  },
  {
    number: 4,
    title: "Review your feedback",
    desc: "After the session, see strengths, areas to improve, and a suggested follow-up question for every answer.",
    detail: "Feedback is generated by the same model that asked the questions — so it's contextual, not generic. Export a PDF summary to keep.",
  },
]

export default function SessionStepper() {
  const { theme } = useTheme()
  const dark = theme === "dark"
  const [active, setActive] = useState(2) // 0-indexed, default step 3

  return (
    <section className="py-24 px-6 max-w-5xl mx-auto">
      <div className="text-center mb-14">
        <p className={`text-xs font-black uppercase tracking-[0.3em] mb-3 ${dark ? "text-blue-400" : "text-blue-600"}`}>
          Tutorial
        </p>
        <h2 className={`text-4xl font-black tracking-tight ${dark ? "text-white" : "text-gray-900"}`}>
          How to run a session
        </h2>
      </div>

      <div className="grid md:grid-cols-[280px,1fr] gap-6 items-start">

        {/* Step list */}
        <div className="flex flex-col gap-2">
          {STEPS.map((s, idx) => {
            const isActive = idx === active
            const isDone   = idx < active
            return (
              <button key={s.number} onClick={() => setActive(idx)}
                className={`flex items-start gap-3 p-3 rounded-2xl text-left transition-all duration-200 ${
                  isActive
                    ? dark ? "bg-indigo-500/15 border border-indigo-500/30" : "bg-indigo-50 border border-indigo-200"
                    : dark ? "hover:bg-white/5 border border-transparent" : "hover:bg-gray-50 border border-transparent"
                }`}
              >
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-black shrink-0 transition-all ${
                  isActive ? "bg-indigo-500 text-white shadow-lg shadow-indigo-500/30"
                  : isDone  ? "bg-emerald-500 text-white"
                  : dark    ? "bg-white/10 text-white/40"
                  :           "bg-gray-200 text-gray-500"
                }`}>
                  {isDone ? "✓" : s.number}
                </div>
                <div>
                  <p className={`font-bold text-sm ${
                    isActive ? "text-indigo-500"
                    : dark   ? "text-white"
                    :          "text-gray-800"
                  }`}>{s.title}</p>
                  <p className={`text-xs mt-0.5 leading-snug ${dark ? "text-white/40" : "text-gray-500"}`}>
                    {s.desc.slice(0, 60)}…
                  </p>
                </div>
              </button>
            )
          })}
        </div>

        {/* Active step detail */}
        <AnimatePresence mode="wait">
          <motion.div
            key={active}
            initial={{ opacity: 0, y: 12, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -12, scale: 0.98 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className={`rounded-3xl p-8 border ${
              dark ? "bg-white/5 border-white/10" : "bg-white/90 border-gray-200 shadow-sm"
            }`}
          >
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-2xl bg-indigo-500 flex items-center justify-center text-white font-black text-lg shadow-lg shadow-indigo-500/30">
                {STEPS[active].number}
              </div>
              <p className={`text-xs uppercase tracking-[0.25em] font-bold ${dark ? "text-white/40" : "text-gray-500"}`}>
                Current Step
              </p>
            </div>
            <h3 className={`text-2xl font-black mb-3 ${dark ? "text-white" : "text-gray-900"}`}>
              {STEPS[active].title}
            </h3>
            <p className={`text-sm leading-relaxed mb-4 ${dark ? "text-white/70" : "text-gray-600"}`}>
              {STEPS[active].desc}
            </p>
            <div className={`rounded-2xl p-4 text-sm leading-relaxed ${
              dark ? "bg-indigo-500/10 border border-indigo-500/20 text-indigo-300"
                   : "bg-indigo-50 border border-indigo-100 text-indigo-700"
            }`}>
              💡 {STEPS[active].detail}
            </div>

            {/* Progress dots */}
            <div className="flex gap-2 mt-6 items-center">
              {STEPS.map((_, i) => (
                <button key={i} onClick={() => setActive(i)}
                  className={`h-2 rounded-full transition-all duration-300 ${
                    i === active ? "w-6 bg-indigo-500" : "w-2 bg-gray-300 dark:bg-white/20"
                  }`}
                />
              ))}
              <button
                onClick={() => setActive(a => Math.min(a + 1, STEPS.length - 1))}
                disabled={active === STEPS.length - 1}
                className="ml-auto text-xs font-bold text-indigo-500 hover:text-indigo-400 disabled:opacity-30 transition-colors"
              >
                Next →
              </button>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </section>
  )
}